### ISSUE TITLE
Plugin "@algolia/netlify-plugin-crawler" internal error

### ISSUE THREAD

**Issue by EmilyFlocc** [algolia/algoliasearch-netlify#713]
I have been using this plugin for almost a year with no issues, but this afternoon my deploys on netlify have been failing with the following error message:

Plugin "@algolia/netlify-plugin-crawler" internal error

Could not import plugin:
/opt/build/repo/web/.netlify/plugins/node_modules/@algolia/netlify-plugin-crawler/src/index.ts:1
import type { NetlifyPluginOptions, NetlifyPluginUtils } from '@netlify/build';
^^^^^^

SyntaxError: Cannot use import statement outside a module

While loading "@algolia/netlify-plugin-crawler" from Netlify app at Object.compileFunction (node:vm:352:18) at wrapSafe (node:internal/modules/cjs/loader:1031:15) at Module._compile (node:internal/modules/cjs/loader:1065:27) at Module._extensions..js (node:internal/modules/cjs/loader:1153:10) at Object.require.extensions.<computed> [as .ts] (/opt/buildhome/node-deps/node_modules/ts-node/src/index.ts:1361:43) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Module.require (node:internal/modules/cjs/loader:1005:19) at require (node:internal/modules/cjs/helpers:102:18) at importLogic (file:///opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/child/logic.js:23:14)

![Screenshot 2022-02-11 at 15 24 12](https://user-images.githubusercontent.com/72082422/153619077-2bf9d4ce-fb72-44d8-9efc-04f80de36145.png)

Does anyone have any ideas what could be causing this or what I can do to fix it?

**Comment by EmilyFlocc** [comment]
Hi @bodinsamuel,

Great, thank you for your help!
