### ISSUE TITLE
Error: Could not reach Algolia's Crawler, got: Forbidden {}

### ISSUE THREAD

**Issue by blackspike** [algolia/algoliasearch-netlify#844]
Hi, I'm struggling to get this working with Nuxt site on Netlify,  any ideas where I'm going wrong? I

My netlify environment variables are

```
ALGOLIA_APPLICATION_ID=YAPTTJ1SIG
ALGOLIA_BASE_URL=https://crawler.algolia.com
ALGOLIA_API_KEY=(secret)
```

My netlify.toml includes the following

```
[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['production']
```
The error in the netlify build

```bash
2:47:04 PM: ────────────────────────────────────────────────────────────────
2:47:04 PM:   5. @algolia/netlify-plugin-crawler (onSuccess event)          
2:47:04 PM: ────────────────────────────────────────────────────────────────
2:47:04 PM: ​
2:47:04 PM: Algolia Netlify plugin started
2:47:04 PM: Sending request to crawl https://crawler.algolia.com/api/1/netlify/crawl
2:47:05 PM: Response {
2:47:05 PM:   size: 0,
2:47:05 PM:   timeout: 0,
2:47:05 PM:   [Symbol(Body internals)]: {
2:47:05 PM:     body: PassThrough {
2:47:05 PM:       _readableState: [ReadableState],
2:47:05 PM:       _events: [Object: null prototype],
2:47:05 PM:       _eventsCount: 5,
2:47:05 PM:       _maxListeners: undefined,
2:47:05 PM:       _writableState: [WritableState],
2:47:05 PM:       allowHalfOpen: true,
2:47:05 PM:       [Symbol(kCapture)]: false,
2:47:05 PM:       [Symbol(kCallback)]: null
2:47:05 PM:     },
2:47:05 PM:     disturbed: false,
2:47:05 PM:     error: null
2:47:05 PM:   },
2:47:05 PM:   [Symbol(Response internals)]: {
2:47:05 PM:     url: 'https://crawler.algolia.com/api/1/netlify/crawl',
2:47:05 PM:     status: 403,
2:47:05 PM:     statusText: 'Forbidden',
2:47:05 PM:     headers: Headers { [Symbol(map)]: [Object: null prototype] },
2:47:05 PM:     counter: 0
2:47:05 PM:   }
2:47:05 PM: }
2:47:05 PM: Could not reach algolia Error: Forbidden {}
2:47:05 PM:     at onSuccess (/opt/build/repo/.netlify/plugins/node_modules/@algolia/netlify-plugin-crawler/dist/index.js:107:19)
2:47:05 PM:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2:47:05 PM:     at async Object.run (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/plugins/child/run.js:14:5)
2:47:05 PM:     at async handleEvent (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/plugins/child/main.js:28:42)
2:47:05 PM:     at async process.<anonymous> (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/plugins/ipc.js:91:24)
2:47:05 PM: ​
2:47:05 PM: ────────────────────────────────────────────────────────────────
2:47:05 PM:   Plugin "@algolia/netlify-plugin-crawler" failed               
2:47:05 PM: ────────────────────────────────────────────────────────────────
2:47:05 PM: ​
2:47:05 PM:   Error message
2:47:05 PM:   Error: Could not reach Algolia's Crawler, got: Forbidden {}
​
2:47:05 PM:   Plugin details
2:47:05 PM:   Package:        @algolia/netlify-plugin-crawler
2:47:05 PM:   Version:        1.0.0
2:47:05 PM:   Repository:     git+https://github.com/algolia/algoliasearch-netlify.git
2:47:05 PM:   npm link:       https://www.npmjs.com/package/@algolia/netlify-plugin-crawler
2:47:05 PM:   Report issues:  https://github.com/algolia/algoliasearch-netlify/issues
2:47:05 PM: ​
2:47:05 PM:   Error location
2:47:05 PM:   In "onSuccess" event in "@algolia/netlify-plugin-crawler" from netlify.toml
2:47:05 PM: ​
2:47:05 PM:   Resolved config
2:47:05 PM:   build:
2:47:05 PM:     command: nuxt generate
2:47:05 PM:     commandOrigin: ui
2:47:05 PM:     environment:
2:47:05 PM:       - ADMIN_PASSWORD
2:47:05 PM:       - ADMIN_SERVER_PASSWORD
2:47:05 PM:       - ADMIN_USERNAME
2:47:05 PM:       - ALGOLIA_API_KEY
2:47:05 PM:       - ALGOLIA_APPLICATION_ID
2:47:05 PM:       - ALGOLIA_BASE_URL
```

**Comment by sbellone** [comment]
Hi, the plugin doesn't use any `ALGOLIA_APPLICATION_ID` env var, where does it comes from? Have you followed the install doc? You can also try to reinstall it from the crawler UI.

**Comment by blackspike** [comment]
I use the `ALGOLIA_APPLICATION_ID`  in my config. I have uninstalled and re-installed the netlify plugin and deleted and recreated the algolia crawler, no joy :(

```bash
12:07:55 PM: Site is live ✨
12:07:56 PM: Finished waiting for live deploy in 58.087152645s
12:07:56 PM: Site deploy was successfully initiated
12:07:56 PM: ​
12:07:56 PM: (Deploy site completed in 1m 19.7s)
12:07:56 PM: ​
12:07:56 PM: ────────────────────────────────────────────────────────────────
12:07:56 PM:   5. @algolia/netlify-plugin-crawler (onSuccess event)          
12:07:56 PM: ────────────────────────────────────────────────────────────────
12:07:56 PM: ​
12:07:56 PM: Algolia Netlify plugin started
12:07:56 PM: Sending request to crawl https://crawler.algolia.com/api/1/netlify/crawl
12:07:56 PM: Response {
12:07:56 PM:   size: 0,
12:07:56 PM:   timeout: 0,
12:07:56 PM:   [Symbol(Body internals)]: {
12:07:56 PM:     body: PassThrough {
12:07:56 PM:       _readableState: [ReadableState],
12:07:56 PM:       _events: [Object: null prototype],
12:07:56 PM:       _eventsCount: 5,
12:07:56 PM:       _maxListeners: undefined,
12:07:56 PM:       _writableState: [WritableState],
12:07:56 PM:       allowHalfOpen: true,
12:07:56 PM:       [Symbol(kCapture)]: false,
12:07:56 PM:       [Symbol(kCallback)]: null
12:07:56 PM:     },
12:07:56 PM:     disturbed: false,
12:07:56 PM:     error: null
12:07:56 PM:   },
12:07:56 PM:   [Symbol(Response internals)]: {
12:07:56 PM:     url: 'https://crawler.algolia.com/api/1/netlify/crawl',
12:07:56 PM:     status: 403,
12:07:56 PM:     statusText: 'Forbidden',
12:07:56 PM:     headers: Headers { [Symbol(map)]: [Object: null prototype] },
12:07:56 PM:     counter: 0
12:07:56 PM:   }
12:07:56 PM: }
12:07:56 PM: Could not reach algolia Error: Forbidden {}
12:07:56 PM:     at onSuccess (/opt/build/repo/.netlify/plugins/node_modules/@algolia/netlify-plugin-crawler/dist/index.js:107:19)
12:07:56 PM:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
12:07:56 PM:     at async Object.run (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/plugins/child/run.js:14:5)
12:07:56 PM:     at async handleEvent (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/plugins/child/main.js:28:42)
12:07:56 PM:     at async process.<anonymous> (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/plugins/ipc.js:91:24)
12:07:56 PM: ​
12:07:56 PM: ────────────────────────────────────────────────────────────────
12:07:56 PM:   Plugin "@algolia/netlify-plugin-crawler" failed               
12:07:56 PM: ────────────────────────────────────────────────────────────────
12:07:56 PM: ​
12:07:56 PM:   Error message
12:07:56 PM:   Error: Could not reach Algolia's Crawler, got: Forbidden {}
​
12:07:56 PM:   Plugin details
12:07:56 PM:   Package:        @algolia/netlify-plugin-crawler
12:07:56 PM:   Version:        1.0.0
12:07:56 PM:   Repository:     git+https://github.com/algolia/algoliasearch-netlify.git
12:07:56 PM:   npm link:       https://www.npmjs.com/package/@algolia/netlify-plugin-crawler
12:07:56 PM:   Report issues:  https://github.com/algolia/algoliasearch-netlify/issues
12:07:56 PM: ​
12:07:56 PM:   Error location
12:07:56 PM:   In "onSuccess" event in "@algolia/netlify-plugin-crawler" from netlify.toml
12:07:56 PM: ​
12:07:56 PM:   Resolved config
12:07:56 PM:   build:
12:07:56 PM:     command: nuxt generate
12:07:56 PM:     commandOrigin: ui
12:07:56 PM:     environment:
12:07:56 PM:       - ADMIN_PASSWORD
12:07:56 PM:       - ADMIN_SERVER_PASSWORD
12:07:56 PM:       - ADMIN_USERNAME
12:07:56 PM:       - ALGOLIA_API_KEY
12:07:56 PM:       - ALGOLIA_APPLICATION_ID
12:07:56 PM:       - ALGOLIA_BASE_URL
12:07:56 PM:       - NPM_FLAGS
12:07:56 PM:       - SUPABASE_KEY
12:07:56 PM:       - SUPABASE_URL
12:07:56 PM:       - cloudflare_account
12:07:56 PM:       - cloudflare_account_hash
12:07:56 PM:       - cloudflare_token
12:07:56 PM:       - google
12:07:56 PM:       - google_map
12:07:56 PM:       - mailgun
12:07:56 PM:       - sheet_id
12:07:56 PM:     publish: /opt/build/repo/dist
12:07:56 PM:     publishOrigin: ui
12:07:56 PM:   functionsDirectory: /opt/build/repo/netlify/functions
12:07:56 PM:   plugins:
12:07:56 PM:     - inputs: {}
12:07:56 PM:       origin: ui
12:07:56 PM:       package: '@netlify/plugin-sitemap'
12:07:56 PM:     - inputs: {}
12:07:56 PM:       origin: config
12:07:56 PM:       package: '@algolia/netlify-plugin-crawler'
12:07:56 PM:   redirects:
12:07:56 PM:     - from: /*
      status: 404
      to: /404
  redirectsOrigin: config
​
12:07:56 PM: ────────────────────────────────────────────────────────────────
12:07:56 PM:   Netlify Build Complete                                        
12:07:56 PM: ────────────────────────────────────────────────────────────────
```

**Comment by sbellone** [comment]
> I use the `ALGOLIA_APPLICATION_ID` in my config

Ok I understand you added it manually then. What about `ALGOLIA_API_KEY`? Was it set by the plugin?

**Comment by blackspike** [comment]
ah, your plugin installs those automatically

[Then, allow Algolia to access your Netlify account. The plugin solely updates your plugin settings and adds necessary environment variables.](https://www.algolia.com/doc/tools/crawler/netlify-plugin/quick-start/)

I've regenerated the ALGOLIA_API_KEY and updated it, same issue

**Comment by sbellone** [comment]
You can't regenerate the `ALGOLIA_API_KEY`, it's generated when you install/reinstall the plugin on your site. The naming is maybe confusing, but this is an internal API key used to control the crawler, not a standard Algolia API key.

**Comment by blackspike** [comment]
Ah interesting! I manually deleted the `ALGOLIA_API_KEY` from my environment variables, deleted the app, reinstalled from scratch and now I get 

```bash
5:31:38 PM: ────────────────────────────────────────────────────────────────
5:31:38 PM:   Plugin "@algolia/netlify-plugin-crawler" failed               
5:31:38 PM: ────────────────────────────────────────────────────────────────
5:31:38 PM: ​
5:31:38 PM:   Error message
5:31:38 PM:   Error: Missing ALGOLIA_API_KEY, please go to https://crawler.algolia.com/admin/netlify to complete your installation.
5:31:38 PM: ​
```

The other day I was prompted by Netlify to upgrade my environment variables to 'the new experience' – I wonder if that is causing Algolia to fail to add the key. Is there a way to access the internal API key? 

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/4052525/203843887-f489a1c1-4cf8-4cec-a445-75dff5484110.png">

**Comment by sbellone** [comment]
Interesting info thanks, we'd have to investigate if the plugin is still compatible with this new experience then.
Just a note: there is a "Reinstall" button in the plugin configuration UI that update those env var.
We don't expose them in the UI on our side.

**Comment by blackspike** [comment]
It was that. I requested netlify support to roll back to the old experience, removed all Algolia env vars, deleted and re-installed the app and it's working again. Thank you for your help!

```
11:46:15 AM: ────────────────────────────────────────────────────────────────
11:46:15 AM:   5. @algolia/netlify-plugin-crawler (onSuccess event)          
11:46:15 AM: ────────────────────────────────────────────────────────────────
11:46:15 AM: ​
11:46:15 AM: Algolia Netlify plugin started
11:46:15 AM: Sending request to crawl https://crawler.algolia.com/api/1/netlify/crawl
11:46:16 AM: API answered: 200
11:46:16 AM: Your crawler is running at: https://crawler.algolia.com/admin/user_configs/xxx
11:46:16 AM: Done.
11:46:16 AM: ​
11:46:16 AM: (@algolia/netlify-plugin-crawler onSuccess completed in 826ms)
```

**Comment by sbellone** [comment]
Thank you very much for confirming that the issue comes from this! We'll have to adapt the plugin then.

**Comment by crimcol** [comment]
I have the same issue.
If you just follow the instruction it will say `Missing ALGOLIA_API_KEY`.
I've tried to reinstall from Algolia UI - does not help.
When you reinstall from Algolia UI it will create a new API_KEY specifically for Netlify, so I decided to manually set it in Environment Variables, but then it says access `Forbidden`.

I've tried to install it from Netlify UI, then it will ask for `ALGOLIA_BASE_URL`, `ALGOLIA_API_KEY`, `ALGOLIA_DISABLED`, but then it says `ALGOLIA_API_KEY` is missing. 

I've tried setting the Admin API key in the Environment variable, but it still says `Forbidden`.

Summary:
When you install the plugin from Netlify UI or Algolia UI - it does not create variables.
When you manually set all required variables in Environment Variables - it says `Forbidden` even it is an Admin API Key.

An error message is basically the same:
```
12:07:56 PM:   Error message
12:07:56 PM:   Error: Could not reach Algolia's Crawler, got: Forbidden {}
```

Any ideas to solve this issue?

**Comment by sbellone** [comment]
Not much to do except rolling back to the old experience like @blackspike did. The plugin needs to be adapted to work with the new experience, thank you for double checking.

**Comment by crimcol** [comment]
> Not much to do except rolling back to the old experience like @blackspike did. The plugin needs to be adapted to work with the new experience, thank you for double checking.

Could you please advise how to rollback?
I'm new to Netlify, so probably I didn't had an old UI.

**Comment by blackspike** [comment]
@crimcol  you have to raise a support ticket in netlify and ask them to roll it back for you, there's no UI for it https://answers.netlify.com/t/opt-out-of-the-new-env-var-experience

**Comment by devraj** [comment]
@blackspike thanks for posting this, I have wasted a few hours figuring out why this wouldn't work.

**Comment by sbellone** [comment]
Hi everyone, sorry for the wait, we finally took time to adapt our backend to the new Netlify APIs! :slightly_smiling_face: 
The plugin is now compatible with the new env vars experience. If you have the error, reinstalling the plugin should solve it.
Thanks again @blackspike for reporting it!

**Comment by brittneypostma** [comment]
I started experiencing this issue today after merging in a branch where I converted to a monorepo. The site was building fine previously off the monorepo branch without issue. The build is still fine, but I am not getting the same plugin error shown in this issue. I have tried disabling then reenabling the plugin and removing the environment variables and manually adding them back after enabling the plugin again. When I removed the environment variables, the plugin did not regenerate a new one, I still had to use the old one. Is there another area this needs to be done in? There is no reinstall option that I see, only disable and enable.

**Comment by sbellone** [comment]
Hi, the reinstall button is on Algolia side: https://crawler.algolia.com/admin/netlify

**Comment by Rahuletto** [comment]
Im sorry, after authorizing with netlify it redirects to algolia account settings. Am i missing something ?

**Comment by sbellone** [comment]
And if you go again to https://crawler.algolia.com/admin/netlify?

**Comment by Rahuletto** [comment]
Yes
